version: '3'
services:

  client:
    container_name: client
    build: ./client 
    ports:
      - "3000:3000"
    networks:
      fullstack:
        ipv4_address: 10.10.20.5
        aliases:
        - client
  server:
    container_name: server
    build: ./server
    ports:
      - "8000:8000"
    networks:
      fullstack:
        ipv4_address: 10.10.20.4
        aliases:
        - server